### ISSUE TITLE
Change friends route to accept an optional item id

### ISSUE THREAD

**Issue by aandis** [rohitpaulk/recommendapp#20]
Given an item, we need to grey out those friends who already have that item recommended.

**Comment by rohitpaulk** [comment]
Why? Shouldn't we allow the person to recommend and then group recommendations?

**Comment by aandis** [comment]
If a person already has an item recommended by someone else and recommendation has been acknowledged, it pretty much means he has used that resources/item. There's no point in him receiving the recommendation again.

**Comment by rohitpaulk** [comment]
Ah. Okay so I'd make the condition not just 'recommended', but whether the person 'has' the item. (Seen the movie, installed the app etc)

**Comment by aandis** [comment]
:beer:
